Check subscription
emitrokhin/temp-http-payment-server pull request #24
Opened 2024-10-29 06:07 UTC by ziplla

2024-10-30 13:20 UTC, emitrokhin requested changes

2024-10-31 21:03 UTC, ziplla commented on src/main/java/ru/emitrohin/paymentserver/service/SubscriptionService.java
>      //TODO рефакторинг + hasPaidSubscription + findCurrent
то есть вернуть как было? не совсем понял просто что убрать
```
public void createPendingSubscription(long telegramId) {
        var subscription = new Subscription();
        subscription.setTelegramId(telegramId);
        subscription.setSubscriptionStatus(SubscriptionStatus.PENDING);
        subscription.setSubscriptionStartDate(LocalDateTime.now());
        subscription.setSubscriptionEndDate(LocalDateTime.now().plusMonths(1));
        subscriptionRepository.save(subscription);
    }

    public void createPaidSubscription(long telegramId) {
        var subscription = new Subscription();
        subscription.setTelegramId(telegramId);
        subscription.setSubscriptionStatus(SubscriptionStatus.PAID);
        subscription.setSubscriptionStartDate(LocalDateTime.now());
        subscriptionRepository.save(subscription);
    }
```

2024-11-02 05:02 UTC, emitrokhin requested changes
Добавил комменты. Класс с проверкой окружения уберем. Не хочу сложностей, так как будем внедрять нормальную библиотеку

2024-11-02 05:02 UTC, emitrokhin commented on src/main/java/ru/emitrohin/paymentserver/client/TelegramBotClient.java
> -        var testEnv = !environment.matchesProfiles("prod");
Давай это вернем

2024-11-02 13:11 UTC, emitrokhin commented on src/test/java/ru/emitrohin/paymentserver/client/TelegramBotClientTest.java
> +        assertEquals(properties.societyId(), requestBody.get("chat_id"));
давай использовать конструкции типа `assertThat`.` isEqualTo `

2024-11-03 07:10 UTC, emitrokhin requested changes

2024-11-03 07:10 UTC, emitrokhin commented on src/main/java/ru/emitrohin/paymentserver/service/SubscriptionService.java
> +                .forEach(subscription -> telegramBotClient.sendMessage(subscription.getTelegramId(),
если у нас `findFirst`, то никакого `forEach`, не должно быть. 

`ifPresent`

2024-11-03 07:10 UTC, emitrokhin commented on src/main/java/ru/emitrohin/paymentserver/service/SubscriptionService.java
> +                .forEach(subscription -> telegramBotClient.sendMessage(subscription.getTelegramId(),
Мне кажется мы можем вынести в обобщенный метод

2024-11-03 07:14 UTC, emitrokhin commented on src/main/java/ru/emitrohin/paymentserver/client/TelegramBotClient.java
> +            var objectMapper = new ObjectMapper();
Только заметил. Нам нужно брать `objectMapper` из спринта, а не самим создавать

2024-11-06 07:45 UTC, emitrokhin approved these changes

2024-11-06 07:45 UTC, merged