Оплата токеном Backend
emitrokhin/temp-http-payment-server pull request #49
Opened 2024-11-13 08:56 UTC by ziplla

2024-11-14 20:23 UTC, emitrokhin requested changes
Нужно пересмотреть структуру PaymentController и вынести это взаимодействие клиентский класс, например, CloudpaymentsClient, а также предусмотреть PaymentProcessingService будет координировать процессы создания и завершения платежа

2024-11-14 20:23 UTC, emitrokhin commented on src/test/resources/application.yaml
> +    cloudPaymentsApiUrl: "https://api.cloudpayments.ru/payments/tokens/charge"
cloudPaymentsApiUrl - вроде докопаться хочется
1) давай уровень вложенности сделаем api:
2) в нем похожем ссылку и выберем название tokensChange

и будет красивая навигация
```yaml
cloudpayments:
    api:
        tokensCharge:
```

2024-11-14 20:26 UTC, emitrokhin commented
@EnableAsync - чтобы облегчить написание асинхронного кода

2024-11-14 20:27 UTC, emitrokhin commented
Вот так вижу сервис обработки и асинхронщину
```java
@Service
@RequiredArgsConstructor
public class PaymentProcessingService {

    private final PaymentService paymentService;
    private final CardService cardService;
    private final CloudPaymentsClient cloudPaymentsClient;

    @Async
    public CompletableFuture<PaymentStatus> processPayment(Long telegramId, UUID cardId) {
        return CompletableFuture.supplyAsync(() -> {
            try {
                // Получаем токен карты
                String cardToken = cardService.getCardById(cardId)
                        .orElseThrow(() -> new RuntimeException("Card not found")).getToken();

                // Вызываем CloudPaymentsClient для выполнения платежа
                boolean success = cloudPaymentsClient.chargeCard(telegramId, cardToken);

                // Определяем статус платежа
                PaymentStatus status = success ? PaymentStatus.SUCCESS : PaymentStatus.FAILED;
                
                // Обновляем статус платежа в базе данных
                UUID paymentId = paymentService.getLastPendingPayment(telegramId)
                        .orElseThrow(() -> new RuntimeException("Payment not found")).getId();
                paymentService.updatePaymentStatus(paymentId, status);

                return status;

            } catch (Exception e) {
                // Логирование ошибки
                UUID paymentId = paymentService.getLastPendingPayment(telegramId)
                        .orElseThrow(() -> new RuntimeException("Payment not found")).getId();
                paymentService.updatePaymentStatus(paymentId, PaymentStatus.FAILED);
                return PaymentStatus.FAILED;
            }
        }).exceptionally(ex -> {
            // В случае исключения устанавливаем статус FAILED и логируем ошибку
            UUID paymentId = paymentService.getLastPendingPayment(telegramId)
                    .orElseThrow(() -> new RuntimeException("Payment not found")).getId();
            paymentService.updatePaymentStatus(paymentId, PaymentStatus.FAILED);
            // Логируем ошибку
            return PaymentStatus.FAILED;
        });
    }
}
```

2024-11-15 19:08 UTC, emitrokhin requested changes
Тесты более детально имеет смысл проверять, когда ты внесёшь изменения

2024-11-15 19:08 UTC, emitrokhin commented on src/test/java/ru/emitrohin/paymentserver/client/CloudPaymentsClientTest.java
> +public class CloudPaymentsClientTest {
Я бы еще проверил HttpStatus 500, вдруг прилетил

2024-11-15 19:08 UTC, emitrokhin commented on src/test/java/ru/emitrohin/paymentserver/service/PaymentProcessingServiceTest.java
> +    private static Card createTestCard(int cardLastFour, String cardExpDate, Boolean isActive, Boolean isPrimary,
У нас очень часто повторяется это действия. Давай вынесем в утилит метод

2024-11-18 11:17 UTC, ziplla commented on src/main/java/ru/emitrohin/paymentserver/controller/rest/PaymentRestController.java
> +    public PaymentStatus getStatus(@PathVariable UUID paymentId) {
согласовали оставить

2024-11-18 19:59 UTC, emitrokhin approved these changes

2024-11-18 20:00 UTC, merged